apiVersion: v1
kind: Service
metadata:
  name: {{ include "on-air-graphics.fullname" . }}
  labels:
    {{- include "on-air-graphics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "on-air-graphics.selectorLabels" . | nindent 4 }}
